name = input("Enter Name: ")
student_class = input("Enter Class: ")
father_name = input("Enter Father's Name: ")
mother_name = input("Enter Mother's Name: ")
email = input("Enter Email: ")
phone = input("Enter Phone: ")
district = input("Enter District: ")
school = input("Enter School: ")
career = input("Enter Career Goal: ")

print("\n--- BIODATA ---")
print("Name:", name)
print("Class:", student_class)
print("Father's Name:", father_name)
print("Mother's Name:", mother_name)
print("Email:", email)
print("Phone:", phone)
print("District:", district)
print("School:", school)
print("Career:", career)